"""empty message

Revision ID: 1ab72d02896e
Revises: f2dbdb56c221
Create Date: 2017-12-02 15:28:55.863000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ab72d02896e'
down_revision = 'f2dbdb56c221'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('url', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_page_url'), 'page', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_url'), table_name='page')
    op.drop_column('page', 'url')
    # ### end Alembic commands ###
