"""empty message

Revision ID: 3697700ab315
Revises: 1ab72d02896e
Create Date: 2017-12-02 16:15:21.803000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3697700ab315'
down_revision = '1ab72d02896e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('body', sa.String(length=1000), nullable=True))
    op.add_column('page', sa.Column('tags', sa.String(length=200), nullable=True))
    op.drop_column('page', 'content')
    op.drop_column('page', 'tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('tag', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('page', sa.Column('content', mysql.VARCHAR(length=1000), nullable=True))
    op.drop_column('page', 'tags')
    op.drop_column('page', 'body')
    # ### end Alembic commands ###
